# Generated by Django 3.0.1 on 2020-01-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
